spring:
  application:
    name: eureka-server
  config:
    import: configserver:${CONFIG_SERVER_URI:http://localhost:8888}
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 2000
        max-attempts: 15
        max-interval: 5000
        multiplier: 1.5

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info
